export const chatsArray = [
    { id: 1, name: "room 1", message: "" },
    { id: 2, name: "room 2", message: "" },
    { id: 3, name: "room 3", message: "" },
    { id: 4, name: "room 4", message: "" },
    { id: 5, name: "room 5", message: "" },
    { id: 6, name: "room 6", message: "" },
    { id: 7, name: "room 7", message: "" },
    { id: 8, name: "room 8", message: "" },
    { id: 9, name: "room 9", message: "" },
    { id: 10, name: "room 10", message: "" },
    { id: 11, name: "room 11", message: "" },
    { id: 12, name: "room 12", message: "" },
    { id: 13, name: "room 13", message: "" },
    { id: 14, name: "room 14", message: "" },
    { id: 15, name: "room 15", message: "" },
    { id: 16, name: "room 16", message: "W" },
    { id: 17, name: "room 17", message: "" },
    { id: 18, name: "room 18", message: "" },
    { id: 19, name: "room 19", message: "" },
    { id: 20, name: "room 20", message: "" },
    { id: 21, name: "room 21", message: "" },
    { id: 22, name: "room 22", message: "" },
    { id: 23, name: "room 23", message: "" },
    { id: 24, name: "room 24", message: "" },
    { id: 25, name: "room 25", message: "" },
    { id: 26, name: "room 26", message: "" },
    { id: 27, name: "room 27", message: "" },
    { id: 28, name: "room 28", message: "" },
    { id: 29, name: "room 29", message: "" },
    { id: 30, name: "room 30", message: "" },
  ];
  