export const chatsArray = [
    { id: 1, name: "Alice", message: "Hello! How can I help you today?" },
    { id: 2, name: "Bob", message: "Just checking in." },
    { id: 3, name: "Charlie", message: "Good morning!" },
    { id: 4, name: "Diana", message: "Have a wonderful day!" },
    { id: 5, name: "Ethan", message: "How are you doing?" },
    { id: 6, name: "Flora", message: "Have a great time!" },
    { id: 7, name: "Gabriel", message: "See you soon!" },
    { id: 8, name: "Hannah", message: "Wishing you all the best!" },
    { id: 9, name: "Isaac", message: "Thank you!" },
    { id: 10, name: "Jessica", message: "You're welcome!" },
    { id: 11, name: "Kevin", message: "Let me know if you need anything." },
    { id: 12, name: "Liam", message: "Happy to help!" },
    { id: 13, name: "Mia", message: "Take care!" },
    { id: 14, name: "Noah", message: "Stay safe!" },
    { id: 15, name: "Olivia", message: "Have a fantastic day!" },
    { id: 16, name: "Sophia", message: "Wishing you success in all your endeavors!" },
    { id: 17, name: "William", message: "Let's chat soon!" },
    { id: 18, name: "Isabella", message: "Hope to see you again soon!" },
    { id: 19, name: "James", message: "Have a blessed day!" },
    { id: 20, name: "Charlotte", message: "Sending you positive vibes!" },
    { id: 21, name: "Aiden", message: "Always here for you!" },
    { id: 22, name: "Mia", message: "You're amazing!" },
    { id: 23, name: "Elijah", message: "Never give up on your dreams!" },
    { id: 24, name: "Evelyn", message: "Believe in yourself!" },
    { id: 25, name: "Lucas", message: "You are capable of achieving anything you set your mind to!" },
    { id: 26, name: "Ava", message: "Remember, you are loved!" },
    { id: 27, name: "Benjamin", message: "Sending you a virtual hug!" },
    { id: 28, name: "Sofia", message: "May your day be filled with joy!" },
    { id: 29, name: "Mason", message: "Keep smiling!" },
    { id: 30, name: "Emily", message: "Thank you for being you!" },
  ];
  